accounts/urls.py
from django.urls import path
from accounts.views import signup_view, login_view, logout_view, \
    ajax_add_message_to_read_group, \
    profile_view, personal_library, loan_request_view, request_history_view, remove_request_ajax, \
    ajax_remove_book_from_reading_state, ajax_user_message_state, user_report_view
from bookshelf.views import ajax_add_book_to_wish_list, ajax_remove_book_from_wish_list, ajax_add_book_to_liked_list, \
    ajax_remove_book_from_liked_list

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('profile/', profile_view, name='profile'),

    path('personal-library/', personal_library, name='personal-library'),
    path('loan-request/book-id=<int:book_id>/', loan_request_view, name='loan-request'),
    path('request-history/', request_history_view, name='request-history'),
    path('remove_request/', remove_request_ajax, name='remove-request'),
    path('user-report-view/', user_report_view, name='user-report-view'),


    path('ajax-add-book-to-wish-list/', ajax_add_book_to_wish_list, name='ajax-add-book-to-wish-list'),
    path('ajax-remove-book-from-wish-list/', ajax_remove_book_from_wish_list, name='ajax-remove-book-from-wish-list'),
    path('ajax-add-book-to-liked-list/', ajax_add_book_to_liked_list, name='ajax-add-book-to-liked-list'),
    path('ajax-remove-book-from-liked-list/', ajax_remove_book_from_liked_list, name='ajax-remove-book-from-liked-list'),



    path('ajax-remove-book-from-reading-state/', ajax_remove_book_from_reading_state, name='ajax-remove-book-from-reading-state'),
    path('ajax_add_message_to_read_group/', ajax_add_message_to_read_group, name='ajax_add_message_to_read_group'),
    path('ajax-user-message-state/', ajax_user_message_state, name='ajax-user-message-state'),
]

negah_2_book_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('tinymce/', include('tinymce.urls')),
    path('', include('bookshelf.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from bookshelf.models import Book, BookProfile
import threading
from django_jalali.db import models as jmodels


class Message(models.Model):
    users = models.ManyToManyField(User, blank=False, verbose_name='کاربران دریافت کننده')
    content = models.TextField(null=False, blank=False, verbose_name='پیام')
    created_at = jmodels.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.content[:50]

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام ها'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False, blank=False, verbose_name='کاربر')
    profile_image = models.ImageField(upload_to='user_profile_pic', null=True, blank=True, verbose_name='عکس پروفایل')
    is_message_seen = models.BooleanField(default=False, null=False, blank=False, verbose_name='آیا نوتیفیکیشن ها خوانده شد؟')
    message_has_seen_at = jmodels.jDateTimeField(null=True, blank=True, editable=False, verbose_name='تاریخ دیدن نوتیفیکیشن ها')
    specific_book_only_for_this_user = models.ManyToManyField(BookProfile, related_name='specific_book_only_for_this_user', verbose_name='کتاب های خاص این کاربر')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'پروفایل کاربر'
        verbose_name_plural = 'پروفایل کاربران'


@receiver(post_save, sender=User)
def auto_create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


class SendNotificationThread(threading.Thread):
    def __init__(self, message_type, users, message_model):
        threading.Thread.__init__(self)
        self.message_type = message_type
        self.users = users
        self.message_model = message_model

    def run(self):
        if self.message_type == 'public':
            for user in self.users:
                user_profile = UserProfile.objects.get(user=user)
                user_profile.notification_box.add(self.message_model)
                user_profile.is_notification_seen = False
                user_profile.save()
        elif self.message_type == 'personal':
            for user in self.users:
                user_profile = UserProfile.objects.get(user=user)
                user_profile.message_box.add(self.message_model)
                user_profile.is_message_seen = False
                user_profile.save()


class UserBookStatus(models.Model):
    user = models.ForeignKey(User, null=False, blank=False, editable=False, on_delete=models.CASCADE, verbose_name='کاربر')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, blank=False, editable=False, verbose_name='کتاب')
    is_reading = models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب در حال مطالعه است؟')
    reading_started_at = jmodels.jDateTimeField(null=True, blank=True, editable=False, verbose_name='تاریخ شروع مطالعه')
    # last_page = models.PositiveIntegerField(default=0, null=False, blank=False, editable=False, verbose_name='آخرین صفحه مطالعه شده')
    # is_finished = models.BooleanField(default=False, editable=False, verbose_name='آیا خواندن کتاب پایان یافته است؟')
    # finish_time = jmodels.jDateTimeField(null=True, blank=True, editable=False, verbose_name='تاریخ پایان مطالعه کتاب')
    # is_Wished = models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب در لیست مطالعه ی آتی است؟')
    # wish_time = jmodels.jDateTimeField(null=True, blank=True, editable=False, verbose_name='تاریخ اضافه شدن به لیست مطالعه اتی')
    # is_liked = models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب جزو موارد مورد علاقه است؟')
    # like_time = jmodels.jDateTimeField(null=True, blank=True, editable=False, verbose_name='تاریخ اضافه شدن به لیست علاقه مندی ها')

    def __str__(self):
        return self.user.username + ' | ' + self.book.title

    class Meta:
        unique_together = ['user', 'book']
        verbose_name = 'ارتباط کاربر و کتاب'
        verbose_name_plural = 'ارتباط کابران و کتاب ها'


class UserBookAssign(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, verbose_name='کاربر')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, blank=False, verbose_name='کتاب')
    date_of_assignment = jmodels.jDateTimeField(auto_now_add=True, verbose_name='تاریخ واگذاری')
    date_of_return = jmodels.jDateTimeField(null=True, blank=True, verbose_name='تاریخ بازگرداندن')

    def __str__(self):
        return self.book.title + " | " + self.user.username

    class Meta:
        verbose_name = 'واگذاری'
        verbose_name_plural = 'واگذاری ها'

accounts/views.py
import re
import jdatetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.cache import never_cache
from text_unidecode import unidecode

from accounts.models import UserProfile, UserBookStatus, Message, UserBookAssign
from bookshelf.models import Book
from contact.models import RequestLoan, AvailableDate


def login_view(request):
    context = {'page_title': 'صفحه ورود'}
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('bookshelf:home')
        else:
            return render(request, 'accounts/sign-in.html', context)
    else:
        if request.user.is_authenticated:
            return redirect('bookshelf:home')
        else:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('bookshelf:home')
            else:
                context['err'] = 'نام کاربری یا کلمه عبور صحیح نمی باشد'
                return render(request, 'accounts/sign-in.html', context)


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('accounts:login')


def signup_view(request):
    context = {'page_title': 'صفحه ثبت نام'}
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('bookshelf:home')
        else:
            return render(request, 'accounts/sign-up.html', context)
    else:
        if request.user.is_authenticated:
            return redirect('bookshelf:home')
        else:
            phone_number = request.POST['phone-number']
            email = request.POST['email']
            full_name = request.POST['full-name']
            password_1 = request.POST['password-1']
            password_2 = request.POST['password-2']

            if phone_number is None:
                context['err'] = 'شماره همراه صحیح نمی باشد'
                return render(request, 'accounts/sign-up.html', context)
            else:
                try:
                    user = User.objects.get(username=phone_number)
                    context['err'] = 'شماره همراه در سامانه موجود می باشد'
                    return render(request, 'accounts/sign-up.html', context)
                except:
                    pass

            if password_1 != password_2:
                context['err'] = 'کلمات عبور وارد شده یکسان نمی باشند'
                return render(request, 'accounts/sign-up.html', context)

            new_user = User.objects.create_user(username=phone_number, email=email, first_name=full_name,
                                                password=password_1, is_active=True)
            login(request, new_user)
            return redirect('bookshelf:home')


def profile_view(request):
    context = {'page_title': 'پروفایل کاربری'}
    if request.user.is_authenticated:
        if request.method == 'GET':
            user_profile = UserProfile.objects.get(user=request.user)
            context['user_profile'] = user_profile
            return render(request, 'profile.html', context)
        else:
            pass
    else:
        return redirect('accounts:login')


def personal_library(request):
    context = {'page_title': 'کتاب خانه من'}
    if request.user.is_authenticated:
        user_book_status = UserBookStatus.objects.filter(user=request.user)
        context['reading_books'] = user_book_status.filter(is_reading=True)
        return render(request, 'personal-library.html', context)
    else:
        return redirect('accounts:login')


def loan_request_view(request, book_id):
    context = {'page_title': 'درخواست امانت فیزیکی کتاب'}
    if request.user.is_authenticated:
        if request.method == 'GET':
            user_profile = UserProfile.objects.get(user=request.user)
            context['user_profile'] = user_profile
            book = Book.objects.get(id=book_id)
            context['book'] = book
            available_dates = AvailableDate.objects.all().order_by('available_date')
            context['available_dates'] = available_dates
            return render(request, 'book-request-loan.html', context)
        else:
            book = Book.objects.get(id=book_id)
            date_of_request = request.POST['date']
            hour = request.POST['hour']
            description = request.POST['description']
            new_request_loan = RequestLoan(
                user=request.user,
                book=book,
                date_of_request=date_of_request,
                hour=hour,
                description=description,
            )
            new_request_loan.save()
            return redirect('accounts:request-history')
    else:
        return redirect('accounts:login')


def remove_request_ajax(request):
    if request.user.is_authenticated:
        user_id = request.POST['user_id']
        user = User.objects.get(id=user_id)
        if user != request.user:
            return HttpResponse('not allowed')
        request_id = request.POST['request_id']
        RequestLoan.objects.get(id=request_id).delete()
        return HttpResponse('ok!')
    else:
        return redirect('accounts:login')


def request_history_view(request):
    context = {'page_title': 'سوابق درخواست ها'}
    if request.user.is_authenticated:
        user_profile = UserProfile.objects.get(user=request.user)
        context['user_profile'] = user_profile
        loan_requests = RequestLoan.objects.filter(user=request.user).order_by('-date_of_request')
        context['loan_requests'] = loan_requests
        return render(request, 'my-request.html', context)
    else:
        return redirect('accounts:login')


def ajax_remove_book_from_reading_state(request):
    if request.user.is_authenticated:
        book_id = request.POST['book_id']
        book = Book.objects.get(id=book_id)
        user_book_status = UserBookStatus.objects.get(user=request.user, book=book)
        user_book_status.is_reading = False
        user_book_status.save()
        return JsonResponse({'message': 'ok'})
    else:
        return redirect('accounts:login')


@never_cache
def ajax_add_message_to_read_group(request):
    if request.user.is_authenticated:
        user_profile = UserProfile.objects.get(user=request.user)
        user_profile.is_message_seen = True
        user_profile.save()
        return HttpResponse('Ok')
    else:
        return redirect('accounts:login')


def ajax_user_message_state(request):
    messages = Message.objects.filter(users__exact=request.user)[:5]
    json_response_body = {
        'is_message_seen': request.user.userprofile.is_message_seen,
        'message_has_seen_at': str(request.user.userprofile.message_has_seen_at),

    }

    messages_dict = {}
    i = 0
    for message in messages:
        messages_dict[i] = {
            'content': message.content,
            'created_at': str(message.created_at.strftime('%Y-%m-%d %H:%M'))
        }
        i += 1
    json_response_body['messages'] = messages_dict
    return JsonResponse(json_response_body)


def user_report_view(request):
    context = {'page_title': 'گزارشات آماری'}
    if request.user.is_authenticated:
        context['custom_range'] = False
        if request.method == 'GET':
            context['today'] = jdatetime.datetime.now().date()
            users = User.objects.all()
            users_book_assign = UserBookAssign.objects.all()
            user_book_status = UserBookStatus.objects.all()

            now = jdatetime.datetime.now()
            this_year = now.year
            this_month = now.month
            user_book_report = []
            date_form = jdatetime.datetime(year=this_year, month=1, day=1)
            for user in users:
                if 1 < this_month < 3:
                    user_book_report.append([user, users_book_assign.filter(user=user,
                                                                            date_of_assignment__range=[
                                                                                date_form,
                                                                                now]).count(), '-',
                                             '-', '-', user_book_status.filter(user=user,
                                                                               reading_started_at__range=[
                                                                                   date_form,
                                                                                   now]).count(), '-',
                                             '-', '-'])


                elif 3 < this_month < 6:
                    date_3_month_to = jdatetime.datetime(year=this_year, month=3, day=31)
                    user_book_report.append([user, users_book_assign.filter(user=user,
                                                                            date_of_assignment__range=[
                                                                                date_form,
                                                                                date_3_month_to]).count(),
                                             users_book_assign.filter(user=user,
                                                                      date_of_assignment__range=[
                                                                          date_form,
                                                                          now]).count(),
                                             '-', '-', user_book_status.filter(user=user,
                                                                               reading_started_at__range=[

templates/accounts/base.html
{% load static %}

<!doctype html>
<html lang="en" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{  page_title }}</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Typography CSS -->
    <link rel="stylesheet" href="{% static 'css/typography.css' %}">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'css/remixicon.css' %}" rel="stylesheet">

    <link href="{% static 'fontawesome-free-6.4.0-web/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free-6.4.0-web/css/brands.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free-6.4.0-web/css/solid.css' %}" rel="stylesheet">
</head>
<body>
<!-- loader Start -->
<div id="loading">
    <div id="loading-center">
    </div>
</div>
<!-- loader END -->
{% block content %}{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Appear JavaScript -->
<script src="{% static 'js/jquery.appear.js' %}"></script>
<!-- Countdown JavaScript -->
<script src="{% static 'js/countdown.min.js' %}"></script>
<!-- Counterup JavaScript -->
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<!-- Wow JavaScript -->
<script src="{% static 'js/wow.min.js' %}"></script>
<!-- Apexcharts JavaScript -->
<script src="{% static 'js/apexcharts.js' %}"></script>
<!-- lottie JavaScript -->
<script src="{% static 'js/lottie.js' %}"></script>
<!-- Slick JavaScript -->
<script src="{% static 'js/slick.min.js' %}"></script>
<!-- Select2 JavaScript -->
<script src="{% static 'js/select2.min.js' %}"></script>
<!-- Owl Carousel JavaScript -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- Magnific Popup JavaScript -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Smooth Scrollbar JavaScript -->
<script src="{% static 'js/smooth-scrollbar.js' %}"></script>
<!-- Style Customizer -->
<script src="{% static 'js/style-customizer.js' %}"></script>
<!-- Chart Custom JavaScript -->
<script src="{% static 'js/chart-custom.js' %}"></script>
<!-- Custom JavaScript -->
<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

templates/accounts/sign-in.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
<section class="sign-in-page">
    <div class="container p-0">
        <div class="row no-gutters height-self-center">
            <div class="col-sm-12 align-self-center page-content rounded">
                <div class="row m-0">
                    <div class="col-sm-12 sign-in-page-data">
                        <div class="sign-in-from bg-primary rounded">
                            <h3 class="mb-0 text-center text-white">ورود به حساب کاربری</h3>
                            <p class="text-center text-white">جهت دسترسی به پنل ایمیل و پسوورد خود را وارد نمایید</p>
                            <form class="mt-4 form-text" action="{% url 'accounts:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">یوزرنیم یا ایمیل</label>
                                    <input type="text" class="form-control mb-0" name="username"
                                           placeholder="یوزرنیم یا ایمیل">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">کلمه عبور</label>
                                    <input type="password" class="form-control mb-0" name="password"
                                           placeholder="کلمه عبور">
                                </div>
                                {% if err %}
                                <div class="form-group text-center text-danger">
                                    <strong>{{ err }}</strong>
                                </div>
                                {% endif %}
                                <div class="sign-info text-center">
                                    <button type="submit" class="btn btn-white d-block w-100 mb-2">ورود</button>
                                    <span class="text-dark dark-color d-inline-block line-height-2">آیا حساب کاربری ندارید؟ <a
                                            href="{% url 'accounts:signup' %}" class="text-white">ساخت حساب کاربری</a></span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/accounts/sign-up.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block content %}
<section class="sign-in-page">
    <div class="container p-0">
        <div class="row no-gutters height-self-center">
            <div class="col-sm-12 align-self-center page-content rounded">
                <div class="row m-0">
                    <div class="col-sm-12 sign-in-page-data">
                        <div class="sign-in-from bg-primary rounded">
                            <h3 class="mb-0 text-center text-white">ثبت نام</h3>
                            <p class="text-center text-white">در کتابخانه انلاین وب اوپس ثبت نام کنید</p>
                            <form class="mt-4 form-text" action="{% url 'accounts:signup' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="phone-number">شماره همراه</label>
                                    <input type="text" class="form-control mb-0" name="phone-number" id="phone-number"
                                           placeholder="شماره همراه" autocomplete="new-password" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">آدرس ایمیل</label>
                                    <input type="email" class="form-control mb-0" name="email" id="email"
                                           placeholder="ایمیل" autocomplete="new-password">
                                </div>
                                <div class="form-group">
                                    <label for="full-name">نام و نام خانوادگی</label>
                                    <input type="text" class="form-control mb-0" name="full-name" id="full-name"
                                           placeholder="نام و نام خانوادگی" autocomplete="new-password">
                                </div>
                                <div class="form-group">
                                    <label for="password-1">کلمه عبور</label>
                                    <input type="password" class="form-control mb-0" name="password-1" id="password-1"
                                           placeholder="کلمه عبور" autocomplete="new-password" required>
                                </div>
                                <div class="form-group">
                                    <label for="password-2">تکرار کلمه عبور</label>
                                    <input type="password" class="form-control mb-0" name="password-2" id="password-2"
                                           placeholder="تکرار کلمه عبور" autocomplete="new-password" required>
                                </div>
                                {% if err %}
                                <div class="form-group text-center text-danger">
                                    <strong>{{ err }}</strong>
                                </div>
                                {% endif %}
                                <div class="sign-info text-center">
                                    <button type="submit" class="btn btn-white d-block w-100 mb-2">ثبت نام</button>
                                    <span class="text-dark d-inline-block line-height-2">آیا حساب کاربری دارید؟ <a
                                            href="{% url 'accounts:login' %}" class="text-white">ورود به حساب کاربری</a></span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}