accounts/urls.py
from django.urls import path
from accounts.views import signup_view, login_view, logout_view, \
    ajax_add_message_to_read_group, \
    profile_view, personal_library, loan_request_view, request_history_view, remove_request_ajax, \
    ajax_remove_book_from_reading_state, ajax_user_message_state, user_report_view
from bookshelf.views import ajax_add_book_to_wish_list, ajax_remove_book_from_wish_list, ajax_add_book_to_liked_list, \
    ajax_remove_book_from_liked_list

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('profile/', profile_view, name='profile'),

    path('personal-library/', personal_library, name='personal-library'),
    path('loan-request/book-id=<int:book_id>/', loan_request_view, name='loan-request'),
    path('request-history/', request_history_view, name='request-history'),
    path('remove_request/', remove_request_ajax, name='remove-request'),
    path('user-report-view/', user_report_view, name='user-report-view'),


    path('ajax-add-book-to-wish-list/', ajax_add_book_to_wish_list, name='ajax-add-book-to-wish-list'),
    path('ajax-remove-book-from-wish-list/', ajax_remove_book_from_wish_list, name='ajax-remove-book-from-wish-list'),
    path('ajax-add-book-to-liked-list/', ajax_add_book_to_liked_list, name='ajax-add-book-to-liked-list'),
    path('ajax-remove-book-from-liked-list/', ajax_remove_book_from_liked_list, name='ajax-remove-book-from-liked-list'),



    path('ajax-remove-book-from-reading-state/', ajax_remove_book_from_reading_state, name='ajax-remove-book-from-reading-state'),
    path('ajax_add_message_to_read_group/', ajax_add_message_to_read_group, name='ajax_add_message_to_read_group'),
    path('ajax-user-message-state/', ajax_user_message_state, name='ajax-user-message-state'),
]

bookshelf/urls.py
from django.urls import path

from bookshelf.views import home_view, book_view, pdf_reader, ajax_pdf_response, book_audio, filter_view

app_name = 'bookshelf'

urlpatterns = [
    path('', home_view, name='home'),
    path('filters/', filter_view, name='filters'),
    path('id=<int:book_id>&name=<str:book_name>/', book_view, name='book_details'),
    path('pdf-reader/id=<int:book_id>&<str:t>/', pdf_reader, name='pdf_reader'),
    path('pdf-data/', ajax_pdf_response, name='pdf_data'),

    path('book-audio/id=<int:book_id>&name=<str:book_name>/', book_audio, name='book-audio'),
]

negah_2_book_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('tinymce/', include('tinymce.urls')),
    path('', include('bookshelf.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ page_title }}</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Typography CSS -->
    <link rel="stylesheet" href="{% static 'css/typography.css' %}">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link href="{% static 'css/remixicon.css' %}" rel="stylesheet">

    <link href="{% static 'fontawesome-free-6.4.0-web/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free-6.4.0-web/css/brands.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free-6.4.0-web/css/solid.css' %}" rel="stylesheet">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extra_head %}
    {% endblock %}
</head>
<body>
<!-- loader Start -->
<div id="loading">
    <div id="loading-center">
    </div>
</div>
<!-- loader END -->
<!-- Wrapper Start -->
<div class="wrapper">
    {% include 'extra/sidebar.html' %}
    {% include 'extra/top-nav-bar.html' %}
    <!-- Page Content  -->
    {% block content %}{% endblock %}
</div>
<!-- Wrapper END -->
{% include 'extra/footer.html' %}

<!-- Optional JavaScript -->

<!-- Appear JavaScript -->
<script src="{% static 'js/jquery.appear.js' %}"></script>
<!-- Countdown JavaScript -->
<script src="{% static 'js/countdown.min.js' %}"></script>
<!-- Counterup JavaScript -->
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<!-- Wow JavaScript -->
<script src="{% static 'js/wow.min.js' %}"></script>
<!-- Apexcharts JavaScript -->
<script src="{% static 'js/apexcharts.js' %}"></script>
<!-- Slick JavaScript -->
<script src="{% static 'js/slick.min.js' %}"></script>
<!-- Select2 JavaScript -->
<script src="{% static 'js/select2.min.js' %}"></script>
<!-- Owl Carousel JavaScript -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- Magnific Popup JavaScript -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Smooth Scrollbar JavaScript -->
<script src="{% static 'js/smooth-scrollbar.js' %}"></script>
<!-- lottie JavaScript -->
<script src="{% static 'js/lottie.js' %}"></script>
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<!-- am animated JavaScript -->
<script src="{% static 'js/animated.js' %}"></script>
<!-- am kelly JavaScript -->
<script src="{% static 'js/kelly.js' %}"></script>
<!-- am maps JavaScript -->
<script src="{% static 'js/maps.js' %}"></script>
<!-- am worldLow JavaScript -->
<script src="{% static 'js/worldLow.js' %}"></script>

<!-- Flatpicker Js -->
<script src="{% static 'js/flatpickr.js' %}"></script>
<!-- Style Customizer -->
<script src="{% static 'js/style-customizer.js' %}"></script>
<!-- Chart Custom JavaScript -->
<script src="{% static 'js/chart-custom.js' %}"></script>
<!-- Custom JavaScript -->
<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

templates/personal-library.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="content-page" class="content-page">
    <div class="container-fluid checkout-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="iq-card">
                    <div class="iq-card-header d-flex justify-content-between iq-border-bottom mb-0">
                        <div class="iq-header-title">
                            <h4 class="card-title">درحال مطالعه</h4>
                        </div>
                    </div>
                    {% for reading_book in reading_books %}
                    <div class="iq-card-body">
                        <ul class="list-inline p-0 m-0">
                            <li class="checkout-product">
                                <div class="row align-items-center">
                                    <div class="col-sm-3 col-lg-2">
                                        <div class="row align-items-center">
                                            <div class="col-sm-3">
                                                <a id="delete-btn" href="javascript:void();" onclick="ajax_remove_book_from_reading_state({{ reading_book.book.id }})" class="badge badge-danger"><i
                                                        class="fa-solid fa-trash mt-1"></i></a>
                                            </div>
                                            <div class="col-sm-9">
                                         <span class="checkout-product-img">
                                         <a href="{% url 'bookshelf:book_details' book_id=reading_book.book.id book_name=reading_book.book.title %}" ><img class="img-fluid rounded"
                                                                               src="{{ reading_book.book.on_paper_image.file_src.url }}"
                                                                               alt="{{ reading_book.book.on_paper_image.file_alt }}"></a>
                                         </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-lg-4">
                                        <div class="checkout-product-details">
                                            <h5>{{ reading_book.book.title }}</h5>
                                            <p style="color: grey"><span>سرشناسه: </span>
                                                {% for author in reading_book.book.authors.all %}
                                                <span>{{ author.full_name }}</span>
                                                {% endfor %}
                                            </p>
                                            <p style="color: grey"><span>پدید آورنده: </span>
                                                {% for interpreter in reading_book.book.interpreters.all %}
                                                <span>{{ interpreter.full_name }}</span>
                                                {% endfor %}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-lg-6">
                                        <div class="row">
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    {% empty %}
                    <div class="iq-card-body">
                        <ul class="list-inline p-0 m-0">
                            <li class="checkout-product">
                                <div class="row align-items-center">
                                    <div class="col-sm-3 col-lg-4">
                                        <b>کتابی برای نمایش وجود ندارد</b>
                                    </div>
                                    <div class="col-sm-6 col-lg-6">
                                        <div class="row">
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="iq-card">
                    <div class="iq-card-header d-flex justify-content-between iq-border-bottom mb-0">
                        <div class="iq-header-title">
                            <h4 class="card-title">خاص شما</h4>
                        </div>
                    </div>
                    {% for reading_book in request.user.userprofile.specific_book_only_for_this_user.all %}
                    <div class="iq-card-body">
                        <ul class="list-inline p-0 m-0">
                            <li class="checkout-product">
                                <div class="row align-items-center">
                                    <div class="col-sm-3 col-lg-2">
                                        <div class="row align-items-center">
                                            <div class="col-sm-9">
                                         <span class="checkout-product-img">
                                         <a href="{% url 'bookshelf:book_details' book_id=reading_book.book.id book_name=reading_book.book.title %}" ><img class="img-fluid rounded"
                                                                               src="{{ reading_book.book.on_paper_image.file_src.url }}"
                                                                               alt="{{ reading_book.book.on_paper_image.file_alt }}"></a>
                                         </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 col-lg-4">
                                        <div class="checkout-product-details">
                                            <h5>{{ reading_book.book.title }}</h5>
                                            <p style="color: grey"><span>سرشناسه: </span>
                                                {% for author in reading_book.book.authors.all %}
                                                <span>{{ author.full_name }}</span>
                                                {% endfor %}
                                            </p>
                                            <p style="color: grey"><span>پدید آورنده: </span>
                                                {% for interpreter in reading_book.book.interpreters.all %}
                                                <span>{{ interpreter.full_name }}</span>
                                                {% endfor %}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 col-lg-6">
                                        <div class="row">
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    {% empty %}
                    <div class="iq-card-body">
                        <ul class="list-inline p-0 m-0">
                            <li class="checkout-product">
                                <div class="row align-items-center">
                                    <div class="col-sm-3 col-lg-4">
                                        <b>کتابی برای نمایش وجود ندارد</b>
                                    </div>
                                    <div class="col-sm-6 col-lg-6">
                                        <div class="row">
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function ajax_remove_book_from_reading_state(book_id) {
    $.ajax({
        method: 'post',
        url: "{% url 'accounts:ajax-remove-book-from-reading-state' %}",
        data: {
            book_id: book_id,
            csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        beforeSend: function () {
            document.getElementById('delete-btn').innerHTML=`<span"><img src="{% static 'custom/loader.gif' %}" style="max-height: 60px; max-width: 60px" }}"></span>`
        },
        error: function (err) {
            document.getElementById('delete-btn').innerHTML=`
            <a id="delete-btn" href="javascript:void();" onclick="ajax_remove_book_from_reading_state(` + book_id + `)" class="badge badge-danger"><i
                                                        class="fa-solid fa-trash"></i></a>
                                                        `
        },
        success: function (data) {
            location.reload()
        },
    })
    return false;
}
</script>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div id="content-page" class="content-page">
        <div class="container-fluid">
            <div class="row profile-content">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="iq-card">
                        <div class="iq-card-body profile-page">
                            <div class="profile-header">
                                <div class="cover-container text-center">
                                    {% if user_profile.profile_image %}
                                    <img src="{{ user_profile.profile_image.url}}" alt="profile-bg" class="rounded-circle img-fluid">
                                    {% else %}
                                    <img src="{% static 'custom/profile.png' %}" alt="profile-bg" class="rounded-circle img-fluid">
                                    {% endif %}
                                    <div class="profile-detail mt-3">
                                        {% if user_profile.user.first_name %}
                                        <h3>{{ user_profile.user.first_name }}</h3>
                                        {% else %}
                                        <h3>{{ user_profile.user.username }}</h3>
                                        {% endif %}
                                        {% if request.user.is_superuser %}
                                        <p class="text-primary">مدیر کل</p>
                                        {% elif request.user.is_staff %}
                                        <p class="text-primary">ادمین</p>
                                        {% else %}
                                        <p class="text-primary">کاربر</p>
                                        {% endif %}
                                        <p></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="iq-card">
                        <div class="iq-card-header d-flex justify-content-between align-items-center mb-0">
                            <div class="iq-header-title">
                                <h4 class="card-title mb-0">اطلاعات کاربری</h4>
                            </div>
                        </div>
                        <div class="iq-card-body">
                            <ul class="list-inline p-0 mb-0">
                                <li>
                                    <div class="row align-items-center justify-content-between mb-3">
                                        <div class="col-sm-6">
                                            <h6>شماره موبایل</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="mb-0">{{ request.user.username }}</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row align-items-center justify-content-between mb-3">
                                        <div class="col-sm-6">
                                            <h6>ایمیل</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="mb-0">{{ request.user.email }}</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="row align-items-center justify-content-between mb-3">
                                        <div class="col-sm-6">
                                            <h6>نام و نام خانوادگی</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="mb-0">{{ request.user.first_name }}</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}